// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"crud-api-wire/api"
	"crud-api-wire/repository"
	"crud-api-wire/service"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func ProductHandler(db *gorm.DB) api.ProductAPI {
	productRepository := repository.ProvideProductRepository(db)
	productService := service.ProvideProductService(productRepository)
	productAPI := api.ProvideProductAPI(productService)
	return productAPI
}
